### PR TITLE
[Added Notes] working of TM to C-T thesis

### PR DESCRIPTION
**Pull request by Kushargs**

### CODE REVIEW

**Review by Zshan0 — CHANGES_REQUESTED** [review]
Could you please add back the topics for which I had written the headings. 
And also can you not put stuff directly from wikipedia, it looks pretty obvious.
Thank you

**Comment by Kushargs** [comment]
ok :(

**Comment by Kushargs** [comment]
That heading was just examples of different variations of TM. You want me to explain them?

**Comment by Zshan0** [comment]
> That heading was just examples of different variations of TM. You want me to explain them?
I want you to write the proof for that equivalency
- k-tape to 1-tape
- any alphabet to basic alphabet

**Comment by Kushargs** [comment]
I have added k-tape to 1-tape. I will change UTM part and add more to it and church-turing thesis tommorow. You can merge it for now.

**Pull request merged**
